import PageLayout from '../../components/PageLayout'
import { PRICING } from '../../config'

/**
 * Terms of Service — UK consumer-law compliant placeholder.
 *
 * Do NOT publish in current state as binding terms. Replace body sections
 * with Termly-generated text (or solicitor-reviewed terms) before launch.
 */
export default function TermsOfService() {
  return (
    <PageLayout title="Terms of Service" lastUpdated="DRAFT — not yet published">
      <div className="page-layout__placeholder">
        <strong>Draft.</strong> This page is a structural scaffold. The
        binding terms text will be generated via Termly (or an equivalent)
        before public launch. Do not rely on the content below as a legal
        contract.
      </div>

      <h2>1. Who we are and what we offer</h2>
      <p>
        ReViva provides an AI-powered interview practice service for surgical
        trainees preparing for UK ST3 specialty selection. Our service
        includes voice-based mock interviews with scored feedback, accessible
        through the web at <a href="https://www.reviva.live">www.reviva.live</a>.
      </p>

      <h2>2. Eligibility</h2>
      <p>
        You must be 18 or older to use this service. By signing up you confirm
        that you are. The service is intended for use by medical professionals
        and trainees; it is not a substitute for formal training or clinical
        advice.
      </p>

      <h2>3. Account responsibilities</h2>
      <ul>
        <li>You are responsible for keeping your login credentials secure.</li>
        <li>You will not share your account or allow others to use it.</li>
        <li>You will provide accurate information when signing up.</li>
        <li>
          You will notify us at{' '}
          <a href="mailto:support@reviva.live">support@reviva.live</a> if you
          suspect unauthorised access.
        </li>
      </ul>

      <h2>4. Subscription and payment</h2>
      <p>
        Premium access is available via subscription. Current pricing:
      </p>
      <ul>
        <li>Monthly: {PRICING.monthly.amount}/month, cancel any time.</li>
        <li>Annual: {PRICING.annual.amount}/year, cancel any time (no refund for unused portion).</li>
      </ul>
      <p>
        Payments are processed by Stripe. We may change pricing for future
        billing cycles with at least 14 days&rsquo; email notice; existing
        subscriptions continue at their original price until renewal.
      </p>

      <h2>5. Refunds and consumer rights</h2>
      <p>
        Under UK consumer law (Consumer Contracts Regulations 2013) you have a
        14-day right to cancel digital services starting from your purchase.
        However, by accessing premium scenarios within those 14 days you
        consent to immediate provision of the digital content and waive the
        cancellation right for content already accessed.
      </p>
      <p>
        <em>
          [Termly: replace this section with vetted text covering refund
          policy, dispute resolution, and CMA-compliant language.]
        </em>
      </p>

      <h2>6. Acceptable use</h2>
      <p>You will not:</p>
      <ul>
        <li>Use the service to harass, threaten, or harm anyone.</li>
        <li>Attempt to gain unauthorised access to our systems.</li>
        <li>Scrape, copy, or republish scenario content or AI examiner output for commercial purposes.</li>
        <li>Use automated tools, scripts, or bots to interact with the service.</li>
        <li>Attempt to extract, reverse-engineer, or copy the underlying prompts, system messages, or AI configurations.</li>
        <li>Resell access to your account.</li>
      </ul>

      <h2>7. Intellectual property</h2>
      <p>
        Scenario content, AI examiner prompts, branding, code, and interface
        designs are owned by ReViva (or licensed to us). You receive a limited,
        non-transferable, non-exclusive licence to access them for personal
        interview preparation. Your own session transcripts remain yours; we
        process them as described in the <a href="/privacy">Privacy Policy</a>.
      </p>

      <h2>8. Service availability</h2>
      <p>
        We aim for high availability but do not guarantee uninterrupted
        service. We rely on third-party providers (Vercel, Render, Supabase,
        Google, Deepgram, Stripe) whose outages may affect availability. We
        will not be liable for losses caused by such outages beyond what UK
        consumer law requires.
      </p>

      <h2>9. AI-generated content disclaimer</h2>
      <p>
        The AI examiner produces responses generated by large language models.
        Although we curate the scenario content and tune the model, the AI may
        produce inaccurate, incomplete, or misleading information. The service
        is for interview practice only and is <strong>not</strong> medical
        advice, clinical decision support, or a substitute for formal training.
        You should not rely on AI responses for any clinical decision.
      </p>

      <h2>10. Limitation of liability</h2>
      <p>
        Nothing in these terms excludes liability for death or personal injury
        caused by our negligence, for fraud, or for any liability that cannot
        be excluded under UK law. Subject to that, our total liability to you
        in any 12-month period is capped at the total amount you paid us in
        that period.
      </p>

      <h2>11. Termination</h2>
      <p>
        You can cancel your subscription and delete your account at any time
        via the <a href="/profile">profile page</a>. We may suspend or
        terminate your account for breach of these terms after notifying you,
        except where suspension is needed immediately for security.
      </p>

      <h2>12. Changes to these terms</h2>
      <p>
        We may update these terms. Material changes will be notified by email
        to active subscribers at least 14 days before they take effect; your
        continued use after that date constitutes acceptance.
      </p>

      <h2>13. Governing law</h2>
      <p>
        These terms are governed by the laws of England and Wales. Disputes
        will be heard in the courts of England and Wales, subject to any
        statutory right of UK consumers to bring claims in their local courts.
      </p>

      <h2>14. Contact</h2>
      <p>
        Questions about these terms:{' '}
        <a href="mailto:support@reviva.live">support@reviva.live</a>.
      </p>
    </PageLayout>
  )
}
