import { Link } from 'react-router-dom'
import PageLayout from '../../components/PageLayout'

/**
 * About page — brand-led story with a bounded founder section.
 *
 * Most content stays in the brand voice. The "Behind ReViva" section is
 * the one place the founder's name/background appears publicly. Keep it
 * factual (training stage, motivation, qualifications relevant to ST3),
 * not personality-driven.
 */
export default function AboutPage() {
  return (
    <PageLayout title="About ReViva" lastUpdated={null}>
      <h2>What we&rsquo;re building</h2>
      <p>
        ReViva is an AI examiner for surgical trainees preparing for UK ST3
        specialty selection. It conducts voice-based mock interviews across
        clinical scenarios, &ldquo;call the boss&rdquo; phone consultations,
        consent stations, and structured-interview stations &mdash; the four
        formats used in real selection panels.
      </p>
      <p>
        The aim is simple: give every trainee unlimited, deliberate
        rehearsal of the situations that actually come up on interview day,
        without needing to corner a consultant for the tenth time this week.
      </p>

      <h2>Why we built it</h2>
      <p>
        ST3 selection is the gate between core training and registrar
        training. The interview is high-stakes, time-limited, and graded
        against a published mark scheme. Almost everyone who sits it has
        done the clinical knowledge work &mdash; the difference between a
        strong score and a borderline one is usually <em>fluency under
        pressure</em>: how you structure an answer, how you handle being
        interrupted, how you redirect when you&rsquo;ve missed a stage.
      </p>
      <p>
        Fluency comes from repetition with feedback. ReViva exists to make
        that repetition cheap, available at midnight, and calibrated to the
        actual panel rubric.
      </p>

      <h2>How it works</h2>
      <ul>
        <li>
          You pick a scenario, a station type, and an examiner difficulty
          (calm, neutral, or strict).
        </li>
        <li>
          The AI conducts a 5&ndash;8 minute interview by voice. It listens,
          asks follow-ups, redirects when you skip a stage, and presses on
          weak answers &mdash; same as a real examiner.
        </li>
        <li>
          At the end you get spoken feedback across six sections (knowledge,
          structure, safety, communication, prioritisation, overall) and a
          0&ndash;5 score calibrated to the panel rubric.
        </li>
        <li>
          You can run the same scenario again at a harder difficulty until
          it&rsquo;s easy.
        </li>
      </ul>

      <h2>What&rsquo;s in the library</h2>
      <p>
        The current release covers plastic surgery ST3 selection, with 100+
        clinical scenarios across hand trauma, burns, skin cancer, head and
        neck, microsurgery, breast and aesthetic, lower limb, congenital,
        and elective hand &mdash; plus consent stations, &ldquo;call the
        boss&rdquo; phone consultations, and structured-interview stations
        (audit, research, teaching, ethics, leadership, risk and safety).
      </p>
      <p>
        Other surgical and non-surgical specialties are on the roadmap.
        Architecture is already specialty-aware so adding the next one is a
        content job, not a rebuild.
      </p>

      <h2>What we don&rsquo;t do</h2>
      <p>
        ReViva is interview practice. It is <strong>not</strong> medical
        advice, clinical decision support, or a substitute for formal
        training. The AI examiner produces responses generated by large
        language models &mdash; we curate the scenario content and tune the
        model, but it can still make mistakes. Don&rsquo;t use it for any
        clinical decision; see the <Link to="/terms">Terms of Service</Link>{' '}
        for full detail.
      </p>

      <h2>Behind ReViva</h2>
      <p>
        <em>
          [Founder note &mdash; replace with your own short bio. Suggested
          structure: 2&ndash;3 sentences covering training stage, the
          experience that motivated this project, relevant qualifications,
          and where to find you if a trainee wants to get in touch. Keep
          it factual rather than self-promotional. Example:]
        </em>
      </p>
      <blockquote>
        I&rsquo;m a UK plastic surgery trainee who built ReViva after sitting
        the ST3 interview myself and realising how thin the realistic
        rehearsal options were &mdash; especially for the &ldquo;think aloud
        under pressure&rdquo; stations. The scenario library, scoring
        rubric, and examiner personalities are all calibrated against the
        published ST3 plastic surgery person specification and the national
        selection mark scheme.
      </blockquote>

      <h2>Get in touch</h2>
      <p>
        Questions, feedback, or partnership ideas: see the{' '}
        <Link to="/contact">contact page</Link>, or email us at{' '}
        <a href="mailto:hello@reviva.live">hello@reviva.live</a>.
      </p>
    </PageLayout>
  )
}
